### ISSUE TITLE
Can't find factory for "entityfishing"

### ISSUE THREAD

**Issue by boskis222** [Lucaterre/spacyfishing#14]
Hello! First of all, thank you for this amazing library. 

Second, I have a problem: whenever I nlp.add_pipe("entityfishing")- I literally used the same code as you-  it shows an error like:

ValueError: [E002] Can't find factory for 'entityfishing' for language German (de). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Any ideas?
Thanks in advance!

**Comment by Lucaterre** [comment]
Hi @boskis222, thanks for your feedback,

can you provide the sample code you are using with spacyfishing? as well as the version of your packages and Python you are using?

Are you using a pretrained NER model from spaCy or your own custom model ?

**Comment by boskis222** [comment]
import spacy  # version 3.3.1
#python version 3.10.7
nlp = spacy.load("en_core_web_lg")

nlp.add_pipe("entityLinker", last=True)

and then the error. of the previous message. I used a virtualenv using my 3.10 python version, and then installed the requirements_dev.txt, so I guess it should be fine. Does it work only with the python version 3.8?

**Comment by Lucaterre** [comment]
thanks @boskis222  for your response :+1: 

Ok, I found several things that may be problematic in your example. 

I propose to you to follow this debugging process and see if you can reproduce this error or not in one of this steps:

1) Why do you use `nlp.add_pipe("entityLinker", last=True)` ? Are you using any other entity linking component than spacyfishing in your pipeline ? First, can you try this basic example code and test if it's work (Cf. [documentation](https://github.com/Lucaterre/spacyfishing/blob/main/README.md)):

```python
import spacy 

# Choose any text
text_en = "Victor Hugo and Honoré de Balzac are French writers who lived in Paris."

# Load your spaCy model
nlp_model_en = spacy.load("en_core_web_sm")

# add linking component to your pipeline
nlp_model_en.add_pipe("entityfishing") # this line replace nlp.add_pipe("entityLinker", last=True)

# apply model
doc_en = nlp_model_en(text_en)

# show results
for ent in doc_en.ents:
        print((ent.text, ent.label_, ent._.kb_qid, ent._.url_wikidata, ent._.nerd_score))
```

2) If the error persists in step 1) try to add `import spacyfishing` statement (because you use the dev_requirements.txt) at the top level of previous code example and run again the script;

3) If the error persists again in step 2) try to use `pip` to install spacyfishing instead of development installation with `pip install spacyfishing` and retry the example code in 1); 

4) I don't think it's an error related to Python version because the package works with Python >= 3.7 but if the error persists in 3) try with Python 3.7 or 3.8 and rerun debugging process;

In your example, I note you use "en_core_web_lg" but in your requirements (pip freeze output) I only see "en_core_web_sm", If you want to use use "en_core_web_lg" instead of "en_core_web_sm", launch the command to install the correct model:

```bash
$ python -m spacy download en_core_web_lg
```

I hope this information can help you

**Comment by boskis222** [comment]
All solved, it was a matter that I was using it in Jupyter Notebook. Ran it on Pycharm and all went smoothly. Thank you so much!
